[project]
name = "mcp-ade-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "agentic-doc>=0.3.3",
    "mcp>=1.13.1",
]
